# Mumu模拟器配置
emulator:
  adb_path: r"D:\Program Files\Netease\MuMuPlayer-12.0\shell\adb.exe"  # ADB可执行文件路径
  mumu_serial': '127.0.0.1:7555' #模拟器设备序列号
  resolution: "1280x720"  # 分辨率
  nickname: "Mumu模拟器"      # 可选标识名称

# 游戏配置
# 1999包名 adb shell cmd package resolve-activity --brief com.shenlan.m.reverse1999
game:
  package_name: "com.shenlan.m.reverse1999"  # 游戏包名
  main_activity: "com.ssgame.mobile.gamesdk.frame.AppStartUpActivity"  # 主Activity


